version: '3.9'

services:
  finantial-manager-db:
    container_name: finantial-manager-db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: finantial_manager
    ports:
      - 5432:5432
    networks:
      - backend

  finantial-manager-api:
    container_name: finantial-manager-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - finantial-manager-db
    environment:
      DB_HOST: finantial-manager-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: finantial_manager
    networks:
      - backend

networks:
  backend: