version: '3.9'

services:
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: finantial_manager
    ports:
      - 5432:5432
    # volumes:
    #   - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: {}